---
      - name: install needed software
        apt:
          name: 
            - python3
            - python3-dev
            - python3-pip
            - git
            - nginx
          state: present

